
import type { Language, MSMEDomain, SalesData, StockData, User } from './types';

export const MOCK_SOCIAL_PROFILES = {
  google: { email: 'google.user@example.com', username: 'Google User', firstname: 'Google' },
  apple: { email: 'apple.user@example.com', username: 'Apple User', firstname: 'Apple' },
  facebook: { email: 'facebook.user@example.com', username: 'Facebook User', firstname: 'Facebook' },
};

export const MSME_DOMAINS: MSMEDomain[] = ['Spinning Mills', 'Knitting and Weaving', 'Dyeing and Finishing', 'Apparel Manufacturing'];

// FIX: Added mock data for dashboard charts
export const MOCK_SALES_DATA: SalesData[] = [
  { month: 'Jan', sales: 400 },
  { month: 'Feb', sales: 300 },
  { month: 'Mar', sales: 500 },
  { month: 'Apr', sales: 700 },
  { month: 'May', sales: 600 },
  { month: 'Jun', sales: 800 },
];

export const MOCK_STOCK_DATA: StockData[] = [
  { date: 'Jan 1', stockLevel: 2400 },
  { date: 'Feb 1', stockLevel: 2210 },
  { date: 'Mar 1', stockLevel: 2290 },
  { date: 'Apr 1', stockLevel: 2000 },
  { date: 'May 1', stockLevel: 2181 },
  { date: 'Jun 1', stockLevel: 2500 },
];

// Demo user configuration - credentials should be set via environment variables
// WARNING: Never hardcode real credentials in production code
type MockUserWithPassword = User & { password?: string };

export const MOCK_USERS: MockUserWithPassword[] = [
  {
    id: 'admin-id',
    email: 'gokulsaravanakumar267@gmail.com',
    password: 'Gokulsha990@',
    username: 'TexConnect Admin',
    firstname: 'Gokul',
    phone: '1234567890',
    address: '123 Admin Lane',
    companyName: 'TexConnect Administration',
    role: 'admin',
    gstNumber: 'ADMIN',
    isApproved: true,
    isEmailVerified: true,
    adminId: 'SUPERADMIN01'
  },
  {
    id: 'msme-1',
    email: 'msme1@example.com',
    username: 'Cotton Mills Ltd',
    firstname: 'Raj',
    phone: '9876543210',
    address: 'Coimbatore, Tamil Nadu',
    companyName: 'Cotton Mills Ltd',
    role: 'msme',
    gstNumber: '33AABCC1234C1Z5',
    isApproved: true,
    isEmailVerified: true,
    domain: 'Spinning Mills'
  },
  {
    id: 'msme-2',
    email: 'msme2@example.com',
    username: 'Textile Weavers',
    firstname: 'Priya',
    phone: '9876543211',
    address: 'Tirupur, Tamil Nadu',
    companyName: 'Textile Weavers Pvt Ltd',
    role: 'msme',
    gstNumber: '33AABCC1234C1Z6',
    isApproved: false,
    isEmailVerified: true,
    domain: 'Knitting and Weaving'
  },
  {
    id: 'buyer-1',
    email: 'buyer1@example.com',
    username: 'Fashion Retail Co',
    firstname: 'Arun',
    phone: '9876543212',
    address: 'Chennai, Tamil Nadu',
    companyName: 'Fashion Retail Co',
    role: 'buyer',
    gstNumber: '33AABCC1234C1Z7',
    isApproved: true,
    isEmailVerified: true
  },
  {
    id: 'buyer-2',
    email: 'buyer2@example.com',
    username: 'Global Exports',
    firstname: 'Meera',
    phone: '9876543213',
    address: 'Bangalore, Karnataka',
    companyName: 'Global Exports Ltd',
    role: 'buyer',
    gstNumber: '29AABCC1234C1Z8',
    isApproved: false,
    isEmailVerified: true
  }
];

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // General
    'texconnect': 'TexConnect',
    'msme_dashboard': 'MSME Dashboard',
    'dashboard': 'Dashboard',
    'inventory': 'Inventory',
    'orders': 'Orders',
    'language': 'Language',
    'english': 'English',
    'tamil': 'Tamil',
    'logout': 'Logout',
    // Auth
    'login': 'Login',
    'register': 'Register',
    'email_address': 'Email Address',
    'password': 'Password',
    'dont_have_account': "Don't have an account?",
    'sign_up': 'Sign Up',
    'already_have_account': 'Already have an account?',
    'full_name': 'Full Name / Business Name',
    'gst_number': 'GST Number',
    'i_am_a': 'I am a...',
    'msme_vendor': 'MSME / Vendor',
    'buyer': 'Buyer',
    'create_account': 'Create Account',
    'login_failed': 'Login failed. Please check your credentials.',
    'registration_successful': 'Registration successful! Please check your email to verify your account.',
    'email_not_verified': 'Your email is not verified. A new verification link has been sent.',
    'resend_verification': 'Resend Verification Email',
    'domain': 'Domain',
    'select_domain': 'Select your domain',
    'spinning_mills': 'Spinning Mills',
    'knitting_and_weaving': 'Knitting and Weaving',
    'dyeing_and_finishing': 'Dyeing and Finishing',
    'apparel_manufacturing': 'Apparel Manufacturing',
    // Pending Approval
    'pending_approval': 'Account Pending Approval',
    'pending_approval_message': 'Your account has been registered and is awaiting approval from an administrator. Please check back later.',
    // Verify Email
    'verify_your_email': 'Verify Your Email',
    'verification_email_sent': 'A verification link has been sent to your email address. Please click the link to activate your account.',
    'simulate_verification': 'Simulate Email Verification',
    // Dashboard View
    'dashboard_overview': 'Dashboard Overview',
    'total_stock_value': 'Total Stock Value',
    'pending_orders': 'Pending Orders',
    'items_in_stock': 'Items in Stock',
    'revenue_this_month': 'Revenue (This Month)',
    'sales_trends': 'Sales Trends',
    'stock_levels': 'Stock Levels',
    'total_products': 'Total Products',
    'current_stock': 'Current Stock',
    'low_stock_items': 'Low Stock Items',
    // Inventory View
    'manage_inventory': 'Manage Inventory',
    'add_new_item': 'Add New Item',
    'product_name': 'Product Name',
    'category': 'Category',
    'stock': 'Stock',
    'price_per_unit': 'Price (₹)/unit',
    'actions': 'Actions',
    'description': 'Description',
    'edit': 'Edit',
    'delete': 'Delete',

    'restock': 'Restock',
    'initial_stock': 'Initial Stock',
    'edit_item': 'Edit Item',
    'save_changes': 'Save Changes',
    'cancel': 'Cancel',
    'confirm_delete': 'Are you sure you want to delete this item?',
    'delete_item': 'Delete Item',
    'unit_of_measure': 'Unit of Measure',
    'minimum_stock_level': 'Minimum Stock Level',
    'stock_alert': 'Low Stock',
    // Orders View
    'track_orders': 'Track Orders',
    'order_id': 'Order ID',
    'buyer_name': 'Buyer Name',
    'date': 'Date',
    'status': 'Status',
    'total': 'Total (₹)',
    'update_status': 'Update Status',
    'no_orders': 'No orders found.',
    'no_inventory': 'No inventory items found. Add one to get started!',
    'buyer_gst': 'Buyer GST',
    // Buyer View
    'buyer_portal': 'Buyer Portal',
    'browse_products': 'Browse Products',
    'my_orders': 'My Orders',
    'search_products': 'Search for products...',
    'place_order': 'Place Order',
    'available_stock': 'Available Stock',
    'quantity': 'Quantity',
    'confirm_order': 'Confirm Order',
    'no_products_found': 'No products found matching your search.',
    'your_orders': 'Your Orders',
    'filter_by_domain': 'Filter by Domain',
    'all_domains': 'All Domains',
    // MSME Profile
    'profile': 'Profile',
    'your_profile': 'Your Profile',
    'edit_profile': 'Edit Profile',
    'pending_changes_message': 'Your profile updates are waiting for an administrator to review and approve them.',
    'gst_certificate': 'GST Certificate',
    'view_certificate': 'View Certificate',
    'not_uploaded': 'Not Uploaded',
    // Invoice
    'invoice': 'Invoice',
    'download_pdf': 'Download PDF',
    'invoice_no': 'Invoice No.',
    'invoice_date': 'Invoice Date',
    'order_date': 'Order Date',
    'bill_to': 'Bill To',
    'ship_to': 'Ship To',
    'item_description': 'Item Description',
    'qty': 'Qty',
    'rate': 'Rate (₹)',
    'amount': 'Amount (₹)',
    'subtotal': 'Subtotal',
    'gst_18': 'GST (18%)',
    'grand_total': 'Grand Total',
    'authorized_signatory': 'Authorized Signatory',
    // Admin View
    'admin_panel': 'Admin Panel',
    'user_management': 'User Management',
    'user_name': 'User Name',
    'role': 'Role',
    'approval_status': 'Approval Status',
    'approve': 'Approve',
    'approved': 'Approved',
    'pending': 'Pending',
    'review_changes': 'Review Changes',
    'approve_changes': 'Approve Changes',
    'reject_changes': 'Reject Changes',
    'current_information': 'Current Information',
    'proposed_changes': 'Proposed Changes',
    'admin_type': 'Admin Type',
    'msme': 'MSME',
    'admin': 'Admin',
    // Approvals
    'msme_approvals': 'MSME Approvals',
    'buyer_approvals': 'Buyer Approvals',
    'admin_management': 'Admin Management',
    'audit_log': 'Audit Log',
    'feedback_logs': 'Feedback Logs',
    'issue_logs': 'Issue Logs',
    'address': 'Address',
    'verified': 'Verified',
    'unverified': 'Unverified',
    'pending_review': 'Pending Review',
    'reject': 'Reject',
    'view': 'View',
    'switch_admin': 'Switch Admin',
    'admin_profile_title': 'Admin Profile',
    'change_photo': 'Change profile picture',
    'settings': 'Settings',
    'loading': 'Loading',
    'login_required_profile': 'Please log in to view profile.',
    'you': 'You',
    'not_set': 'Not set',
    'uploading': 'Uploading',
    'error': 'Error',
    'profile_updated_success': 'Profile updated successfully!',
    'enter_username': 'Enter your username',
    'enter_phone': 'Enter your phone number',
    'enter_address': 'Enter your address',
    'saving': 'Saving',
    'quick_actions': 'Quick Actions',
    'system_overview': 'System Overview',
    'system_status': 'System Status',
    'database_connected': 'Database Connected',
    'online': 'Online',
    'system_performance': 'System Performance',
    'optimal': 'Optimal',
    'pending_tasks': 'Pending Tasks',
    'users_pending_verification': 'Users pending verification',
    'no_pending_tasks': 'No pending tasks.',
    'low_stock': 'low stock',
    'orders_count': 'orders',
    'order_placed': 'Order placed',
    'stock_updated': 'Stock updated',
    'item_shipped': 'Item shipped',
    'new_product_added': 'New product added',
    'approved_status': 'Approved',
    'pending_approval_status': 'Pending Approval',
    'add_inventory_action': 'Add Inventory',
    'new_order_action': 'New Order',
    'export_report_action': 'Export Report',
    'view_alerts_action': 'View Alerts',
    'just_now': 'Just now',
    'min_ago': 'min ago',
    'h_ago': 'h ago',
    'd_ago': 'd ago',
    'back': 'Back',
    'welcome_back_login': 'Welcome Back!',
    'join_texconnect': 'Join TexConnect',
    'login_description': 'Smart inventory management for Tiruppur textile manufacturers. Track yarn, fabric, and garments seamlessly.',
    'signup_description': 'Start managing your textile inventory digitally. Join 850+ Tiruppur manufacturers already using TexConnect.',
    'create_account_btn': 'CREATE ACCOUNT',
    'sign_in_btn': 'SIGN IN',
    'login_title': 'LOGIN',
    'enter_email_placeholder': 'Enter your email',
    'enter_password_placeholder': 'Enter your password',
    'forgot_password': 'Forgot Password?',
    'or_login_with': 'Or Login with',
    'signup_title': 'SIGN UP',
    'buyer_role': 'Buyer',
    'msme_role': 'MSME',
    'first_name': 'First Name',
    'enter_firstname_placeholder': 'Enter your first name',
    'choose_username_placeholder': 'Choose a username',
    'enter_phone_placeholder': 'Enter your phone number',
    'business_domain': 'Business Domain',
    'create_password_placeholder': 'Create a password',
    'confirm_password': 'Confirm Password',
    'confirm_password_placeholder': 'Confirm your password',
    'agree_terms': 'I agree to the terms and conditions',
    'reset_password_title': 'Reset Password',
    'reset_password_desc': 'Enter your email address and we will send you a link to reset your password.',
    'send_reset_link': 'Send Reset Link',
    'check_email_reset': 'Check your email for password reset instructions.',
    'return_to_login': 'Return to Login',
    // Company Profile
    'company_profile': 'Company Profile',
    'choose_company_photo': 'Choose company profile photo',
    'company_name': 'Company Name',
    'contact_person': 'Contact Person',
    'email': 'Email',
    'phone': 'Phone',
    // Issues Page
    'issues': 'Issues',
    'report_issue': 'Report Issue',
    'issue_title': 'Issue Title',
    'issue_description': 'Issue Description',
    'issue_category': 'Issue Category',
    'issue_priority': 'Issue Priority',
    'active_issues': 'Active Issues',
    'resolved_issues': 'Resolved Issues',
    'no_issues': 'No issues',
    'report_new_issue': 'Report New Issue',
    // Buyer Dashboard - New Keys
    'buyer_dashboard': 'Buyer Dashboard',
    'browse_products_title': 'Browse Products',
    'my_orders_title': 'My Orders',
    'report_issue_title': 'Report Issue',
    'my_profile_title': 'My Profile',
    'total_orders_stat': 'Total Orders',
    'all_time_orders': 'All time orders',
    'pending_orders_stat': 'Pending Orders',
    'awaiting_delivery': 'Awaiting delivery',
    'completed_orders_stat': 'Completed Orders',
    'successfully_delivered': 'Successfully delivered',
    'total_spent': 'Total Spent',
    'lifetime_spending': 'Lifetime spending',
    'welcome_back': 'Welcome back',
    'discover_quality_products': 'Discover quality textile products from verified MSMEs',
    'start_shopping': 'Start Shopping',
    // Admin Dashboard - New Keys
    'admin_dashboard': 'Admin Dashboard',
    'total_users': 'Total Users',
    'buyers_stat': 'Buyers',
    'verified_users': 'Verified Users',
    'manage_users': 'Manage Users',
    'view_issues': 'View Issues',
    'audit_logs': 'Audit Logs',
    'user_feedback': 'User Feedback',
    'my_products': 'My Products',
    'active_products': 'Active Products',
    'inactive_products': 'Inactive Products',
    'visible_to_buyers': 'Visible to Buyers',
    'no_products_yet': 'No products yet',
    'add_products_to_showcase': 'Add products to showcase',
    'update_product': 'Update Product',
    'delete_product': 'Delete Product',
    'go_to_inventory_to_add_products': 'Manage inventory to add products',
    'inactive_or_out_of_stock': 'Inactive or Out of Stock',
    'inactive': 'Inactive',
    'active': 'Active',
    'yes': 'Yes',
    'no': 'No',
    'active_status': 'Active',
    'inactive_status': 'Inactive',
    'add_inventory_to_msme': 'Add inventory to MSME',
    'tax_invoice': 'TAX INVOICE',
    'original_for_recipient': 'Original for Recipient',
    'seller_details': 'Seller Details',
    'buyer_details': 'Buyer Details',
    'material_description': 'Material Description',
    's_no': 'S.No',
    'uom': 'UOM',
    'total_amount': 'Total Amount',
    'terms_conditions': 'Terms & Conditions',
    'computer_generated_invoice': 'This is a computer-generated invoice and does not require a signature.',
    'payment_terms': 'Payment is due within 30 days of invoice date.',
    'goods_sold_terms': 'Goods once sold will not be taken back or exchanged.',
    'dispute_terms': "All disputes are subject to jurisdiction of courts in seller's location.",
    'interest_terms': 'Interest @18% p.a. will be charged on delayed payments.',
    'msme_profile': 'MSME Profile',
    'add_inventory': 'Add Inventory',
    'uploading_profile_photo': 'Uploading profile photo...',
    'inventory_item_added': 'Inventory item added successfully!',
    'file_size_error': 'File size must be less than 5MB',
    'invalid_image_error': 'Please select a valid image file',
    'invalid_gst_file_error': 'Please upload a JPEG or PDF file',
    'attn': 'Attn',
    'for': 'For',
    'generated_on': 'Generated on',
    'my_issues_complaints': 'My Issues & Complaints',
    'no_active_issues': 'No active issues',
    'no_resolved_issues': 'No resolved issues',
    'admin_response': 'Admin Response',
    'user_profile_details': 'User Profile Details',
    'confirm_profile_update': 'Confirm Profile Update',
    'profile_update_confirm_message': 'Are you sure you want to update your profile? Some changes may require re-verification.',
    'login_as_guest': 'Login as Guest',
    'approve_user': 'Approve User',
    'approving': 'Approving...',
    'failed_approve_user': 'Failed to approve user',
    'close': 'Close',
    'stock_utilization': 'Stock Utilization',
    'overall_stock_usage': 'Overall Stock Usage',
    'units_utilized': 'units utilized',
    'out_of_stock': 'Out of Stock',
    'critical': 'Critical',
    'low': 'Low',
    'good': 'Good',
    'view_update_catalog': 'View and update your product catalog',
    'restock_product': 'Restock Product',
    'enter_quantity_add': 'Enter quantity to add',
    'placing_order': 'Placing order...',
    'search_products_or_suppliers': 'Search products or suppliers...',
    'sort_by': 'Sort by',
    'sort_by_name': 'Sort by Name',
    'sort_by_price': 'Sort by Price',
    'sort_by_stock': 'Sort by Stock',
    'off_line_mode': 'You are offline',
    'viewing_cached_data': 'Viewing cached data. Some features may be limited.',
    'reserved': 'Reserved',
    'available': 'Available',
    'bought_total_cost': 'Bought (Total Cost)',
    'track_manage_inventory': 'Track and manage your textile inventory',
    'smart_description': 'Smart Description',
    'generating': 'Generating...',
    'permanent_deletion': 'Permanent Deletion',
    'action_cannot_be_undone': 'This action cannot be undone.',
    'manage_fulfill_orders': 'Manage and fulfill your incoming orders',
    'qr_sticker': 'QR Sticker',
    'retrieve': 'Retrieve',
    'buyer_gst_number': 'Buyer GST Number',
    'item_name': 'Item Name',
    'live_data': 'Live Data',
    'adding': 'Adding...',
    'loading_inventory_data': 'Loading inventory data...',
    'this_may_take_seconds': 'This may take a few seconds...',
    'unable_load_stats': 'Unable to load inventory statistics',
    'stock_quantity': 'Stock Quantity',
    'items': 'Items',
    'of': 'of',
    'units_utilized_message': 'units utilized (sold/reserved)',
    'enter_name_category': 'Please enter a product name and category first.',
    'failed_generate_description': 'Failed to generate description. Please try again.',
    'failed_save_item': 'Failed to save item. Please try again.',
    'failed_delete_item': 'Failed to delete item. Please try again.',
    'product_name_placeholder': 'e.g. Combed Cotton Yarn',
    'category_placeholder': 'e.g. Raw Material',
    'description_placeholder': 'A short, catchy description...',
    'total_spent_placeholder': '₹ Total spent',
    'uom_placeholder': 'e.g. Kg, Piece',
    'describe_your_product': 'Describe your product...',
    'inventory_restocked_success': 'Product restocked successfully!',
    'inventory_item_added_success': 'Inventory item added successfully!',
    'error_restocking': 'Error restocking product',
    'new_stock': 'New stock',
    'error_placing_order': 'There was an error placing your order. Please try again.',
    'showing_other_domains': 'Showing products from other domains only',
    'units_label': 'Units',
    'failed_update_status': 'Failed to update status',
    'not_applicable': 'N/A',
    'please_try_again': 'Please try again',
    'restock_needed_immediately': 'Restock needed immediately',
    'confirm_restock': 'Confirm Restock',
    'units': 'Units',
    'total_stock': 'Total Stock',
    'by': 'by',
    'product': 'Product',
  },
  ta: {
    // General
    'texconnect': 'டெக்ஸ்கனெக்ட்',
    'msme_dashboard': 'குறு, சிறு மற்றும் நடுத்தர நிறுவன டாஷ்போர்டு',
    'dashboard': 'டாஷ்போர்டு',
    'inventory': 'சரக்கு',
    'orders': 'ஆர்டர்கள்',
    'language': 'மொழி',
    'english': 'ஆங்கிலம்',
    'tamil': 'தமிழ்',
    'logout': 'வெளியேறு',
    // Auth
    'login': 'உள்நுழை',
    'register': 'பதிவு செய்',
    'email_address': 'மின்னஞ்சல் முகவரி',
    'password': 'கடவுச்சொல்',
    'dont_have_account': 'கணக்கு இல்லையா?',
    'sign_up': 'பதிவு செய்க',
    'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'full_name': 'முழு பெயர் / வணிகப் பெயர்',
    'gst_number': 'ஜிஎஸ்டி எண்',
    'i_am_a': 'நான் ஒரு',
    'msme_vendor': 'குறு, சிறு மற்றும் நடுத்தர தொழில் / விற்பனையாளர்',
    'buyer': 'வாங்குபவர்',
    'create_account': 'கணக்கை உருவாக்கு',
    'login_failed': 'உள்நுழைவு தோல்வியடைந்தது. உங்கள் சான்றுகளைச் சரிபார்க்கவும்.',
    'registration_successful': 'பதிவு வெற்றி பெற்றது! உங்கள் கணக்கைச் சரிபார்க்க உங்கள் மின்னஞ்சலைச் சரிபார்க்கவும்.',
    'email_not_verified': 'உங்கள் மின்னஞ்சல் சரிபார்க்கப்படவில்லை. ஒரு புதிய சரிபார்ப்பு இணைப்பு அனுப்பப்பட்டுள்ளது.',
    'resend_verification': 'சரிபார்ப்பு மின்னஞ்சலை மீண்டும் அனுப்பு',
    'domain': 'களம்',
    'select_domain': 'டொமைனைத் தேர்ந்தெடுக்கவும்',
    'spinning_mills': 'நூற்பு ஆலைகள்',
    'knitting_and_weaving': 'பின்னல் மற்றும் நெசவு',
    'dyeing_and_finishing': 'சாயமிடுதல் மற்றும் முடித்தல்',
    'apparel_manufacturing': 'ஆடை உற்பத்தி',
    // Pending Approval
    'pending_approval': 'கணக்கு ஒப்புதலுக்காக காத்திருக்கிறது',
    'pending_approval_message': 'உங்கள் கணக்கு பதிவு செய்யப்பட்டு நிர்வாகியின் ஒப்புதலுக்காக காத்திருக்கிறது. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪರಿಶೀಲಿಸಿ.',
    // Verify Email
    'verify_your_email': 'உங்கள் மின்னஞ்சலைச் சரிபார்க்கவும்',
    'verification_email_sent': 'உங்கள் மின்னஞ்சல் முகவரிக்கு ஒரு சரிபார்ப்பு இணைப்பு அனுப்பப்பட்டுள்ளது. உங்கள் கணக்கைச் செயல்படுத்த இணைப்பைக் கிளிக் செய்யவும்.',
    'simulate_verification': 'மின்னஞ்சல் சரிபார்ப்பை உருவகப்படுத்துங்கள்',
    // Dashboard View
    'dashboard_overview': 'டாஷ்போர்டு கண்ணோட்டம்',
    'total_stock_value': 'மொத்த சரக்கு மதிப்பு',
    'pending_orders': 'நிலுவையில் உள்ள ஆர்டர்கள்',
    'items_in_stock': 'கையிருப்பில் உள்ள பொருட்கள்',
    'revenue_this_month': 'வருவாய் (இந்த மாதம்)',
    'sales_trends': 'விற்பனை போக்குகள்',
    'stock_levels': 'சரக்கு நிலைகள்',
    'total_products': 'மொத்த தயாரிப்புகள்',
    'current_stock': 'தற்போதைய இருப்பு',
    'low_stock_items': 'குறைந்த இருப்பு பொருட்கள்',
    // Inventory View
    'manage_inventory': 'சரக்குகளை நிர்வகி',
    'add_new_item': 'புதிய பொருளைச் சேர்',
    'product_name': 'பொருளின் பெயர்',
    'category': 'வகை',
    'stock': 'சரக்கு',
    'price_per_unit': 'விலை (₹)/அலகு',


    'restock': 'சரக்கை நிரப்பு',
    'initial_stock': 'ஆரம்ப இருப்பு',
    'edit_item': 'பொருளைத் திருத்து',
    'save_changes': 'மாற்றங்களைச் சேமி',
    'cancel': 'ரத்துசெய்',
    'confirm_delete': 'இந்த பொருளை நீக்க விரும்புகிறீர்களா?',
    'delete_item': 'பொருளை நீக்கு',
    'unit_of_measure': 'அளவீட்டு அலகு',
    'minimum_stock_level': 'குறைந்தபட்ச இருப்பு நிலை',
    'stock_alert': 'குறைந்த இருப்பு',
    // Orders View
    'track_orders': 'ஆர்டர்களைக் கண்காணி',
    'order_id': 'ஆர்டர் ஐடி',
    'buyer_name': 'வாங்குபவர் பெயர்',
    'date': 'தேதி',
    'status': 'நிலை',
    'total': 'மொத்தம் (₹)',
    'update_status': 'நிலையை மாற்று',
    'no_orders': 'ஆர்டர்கள் எதுவும் இல்லை.',
    'no_inventory': 'சரக்குப் பொருட்கள் எதுவும் இல்லை. தொடங்குவதற்கு ஒன்றைச் சேர்க்கவும்!',
    'buyer_gst': 'வாங்குபவர் ஜிஎஸ்டி',
    // Buyer View
    'buyer_portal': 'வாங்குபவர் போர்டல்',
    'browse_products': 'தயாரிப்புகளை உலாவுக',
    'my_orders': 'என் ಆದೇಶங்கள்',
    'search_products': 'தயாரிப்புகளைத் தேடுங்கள்...',
    'place_order': 'ஆர்டர் செய்',
    'available_stock': 'கிடைக்கும் சரக்கு',
    'quantity': 'அளவு',
    'confirm_order': 'உறுதி செய்',
    'no_products_found': 'உங்கள் தேடலுடன் பொருந்தும் தயாரிப்புகள் எதுவும் இல்லை.',
    'your_orders': 'உங்கள் ஆர்டர்கள்',
    'filter_by_domain': 'களம் வாரியாக வடிகட்டவும்',
    'all_domains': 'அனைத்து களங்களும்',
    // MSME Profile
    'profile': 'சுயவிவரம்',
    'your_profile': 'உங்கள் சுயவிவரம்',
    'edit_profile': 'சுயவிவரத்தைத் திருத்து',
    'pending_changes_message': 'உங்கள் சுயவிவரப் புதுப்பிப்புகள் நிர்வாகி மதிப்பாய்வு செய்து ஒப்புதல் அளிப்பதற்காகக் காத்திருக்கின்றன.',
    'gst_certificate': 'ஜிஎஸ்டி சான்றிதழ்',
    'view_certificate': 'சான்றிதழைப் காண்க',
    'not_uploaded': 'பதிவேற்றப்படவில்லை',
    // Invoice
    'invoice': 'விலைப்பட்டியல்',
    'download_pdf': 'PDF பதிவிறக்கம்',
    'invoice_no': 'விலைப்பட்டியல் எண்.',
    'invoice_date': 'விலைப்பட்டியல் தேதி',
    'order_date': 'ஆர்டர் தேதி',
    'bill_to': 'யாருக்கு பட்டியல்',
    'ship_to': 'யாருக்கு அனுப்பவேண்டியது',
    'item_description': 'பொருள் விவரம்',
    'qty': 'அளவு',
    'rate': 'விகிதம் (₹)',
    'amount': 'தொகை (₹)',
    'subtotal': 'மொத்த தொகை',
    'gst_18': 'ஜிஎஸ்டி (18%)',
    'grand_total': 'மொத்த கூட்டுத்தொகை',
    'authorized_signatory': 'அங்கீகரிக்கப்பட்ட கையொப்பமிட்டவர்',
    // Admin View
    'admin_panel': 'நிர்வாக குழு',
    'user_management': 'பயனர் மேலாண்மை',
    'user_name': 'பயனர் பெயர்',
    'role': 'பங்கு',
    'approval_status': 'ஒப்புதல் நிலை',
    'approve': 'ஒப்புதல்',
    'approved': 'ஒப்புதல் அளிக்கப்பட்டது',
    'pending': 'நிலுவையில்',
    'review_changes': 'மாற்றங்களை மதிப்பாய்வு செய்',
    'approve_changes': 'மாற்றங்களை அங்கீகரிக்கவும்',
    'reject_changes': 'மாற்றங்களை நிராகரிக்கவும்',
    'current_information': 'தற்போதைய தகவல்',
    'proposed_changes': 'பரிந்துரைக்கப்பட்ட மாற்றங்கள்',
    'admin_type': 'நிர்வாகி வகை',
    'msme': 'MSME',
    'admin': 'நிர்வாகி',
    // Approvals
    'msme_approvals': 'MSME ஒப்புதல்கள்',
    'buyer_approvals': 'வாங்குபவர் ஒப்புதல்கள்',
    'admin_management': 'நிர்வாகி மேலாண்மை',
    'audit_log': 'தணிக்கை பதிவு',
    'feedback_logs': 'கருத்து பதிவுகள்',
    'issue_logs': 'சிக்கல் பதிவுகள்',
    'address': 'முகவரி',
    'verified': 'சரிபார்க்கப்பட்ட',
    'unverified': 'சரிபார்க்கப்படவில்லை',
    'pending_review': 'மதிப்பாய்வு நிலுவையில் உள்ளது',
    'reject': 'நிராகரிக்க',
    'view': 'பார்க்க',
    'switch_admin': 'நிர்வாகியை மாற்றவும்',
    'admin_profile_title': 'நிர்வாக சுயவிவரம்',
    'change_photo': 'சுயவிவரப் படத்தை மாற்றவும்',
    'settings': 'அமைப்புகள்',
    'loading': 'ஏற்றுகிறது',
    'login_required_profile': 'சுயவிவரத்தைப் பார்க்க உள்நுழையவும்.',
    'you': 'நீங்கள்',
    'not_set': 'அமைக்கப்படவில்லை',
    'uploading': 'பதிவேற்றுகிறது',
    'error': 'பிழை',
    'profile_updated_success': 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    'enter_username': 'உங்கள் பயனர் பெயரை உள்ளிடவும்',
    'enter_phone': 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
    'enter_address': 'உங்கள் முகவரியை உள்ளிடவும்',
    'saving': 'சேமிக்கிறது',
    'quick_actions': 'விரைவான நடவடிக்கைகள்',
    'system_overview': 'அமைப்பு மேலோட்டம்',
    'system_status': 'அமைப்பு நிலை',
    'database_connected': 'தரவுத்தளம் இணைக்கப்பட்டுள்ளது',
    'online': 'ஆன்லைன்',
    'system_performance': 'அமைப்பு செயல்திறன்',
    'optimal': 'உகந்த',
    'pending_tasks': 'நிலுவையில் உள்ள பணிகள்',
    'users_pending_verification': 'பயனர்கள் சரிபார்ப்பு நிலுவையில் உள்ளது',
    'no_pending_tasks': 'நிலுவையில் உள்ள பணிகள் இல்லை.',
    'low_stock': 'குறைந்த இருப்பு',
    'orders_count': 'ஆர்டர்கள்',
    'order_placed': 'ஆர்டர் செய்யப்பட்டது',
    'stock_updated': 'இருப்பு புதுப்பிக்கப்பட்டது',
    'item_shipped': 'பொருள் அனுப்பப்பட்டது',
    'new_product_added': 'புதிய தயாரிப்பு சேர்க்கப்பட்டது',
    'approved_status': 'அங்கீகரிக்கப்பட்டது',
    'pending_approval_status': 'ஒப்புதலுக்காக காத்திருக்கிறது',
    'add_inventory_action': 'சரக்குகளைச் சேர்',
    'new_order_action': 'புதிய ஆர்டர்',
    'export_report_action': 'அறிக்கையை ஏற்றுமதி செய்',
    'view_alerts_action': 'எச்சரிக்கைகளைப் பார்க்கவும்',
    'just_now': 'இப்பொழுது',
    'min_ago': 'நிமிடங்களுக்கு முன்',
    'h_ago': 'மணிநேரங்களுக்கு முன்',
    'd_ago': 'நாட்களுக்கு முன்',
    // Company Profile
    'company_profile': 'நிறுவன சுயவிவரம்',
    'choose_company_photo': 'நிறுவன சுயவிவர புகைப்படத்தைத் தேர்ந்தெடுக்கவும்',
    'company_name': 'நிறுவன பெயர்',
    'contact_person': 'தொடர்பு நபர்',
    'email': 'மின்னஞ்சல்',
    'phone': 'தொலைபேசி',
    // Issues Page
    'issues': 'சிக்கல்கள்',
    'report_issue': 'சிக்கலைப் புகாரளி',
    'issue_title': 'சிக்கலின் தலைப்பு',
    'issue_description': 'சிக்கலின் விளக்கம்',
    'issue_category': 'சிக்கலின் வகை',
    'issue_priority': 'சிக்கலின் முன்னுரிமை',
    'active_issues': 'செயல்பாட்டில் உள்ள சிக்கல்கள்',
    'resolved_issues': 'தீர்க்கப்பட்ட சிக்கல்கள்',
    'no_issues': 'சிக்கல்கள் இல்லை',
    'report_new_issue': 'புதிய சிக்கலைப் புகாரளி',
    'actions': 'நடவடிக்கைகள்',
    'accept': 'ஏற்கவும்',
    'retrieve': 'மீட்டெடுக்கவும்',
    'qr_sticker': 'QR ஸ்டிக்கர்',
    'shipped': 'அனுப்பப்பட்டது',
    'delivered': 'விநியோகிக்கப்பட்டது',
    'accepted': 'ஏற்றுக்கொள்ளப்பட்டது',
    'cancelled': 'ரத்து செய்யப்பட்டது',
    'back_to_inventory': 'சிரிப்புக்குத் திரும்பு',
    'back_to_dashboard': 'டாஷ்போர்டுக்குத் திரும்பு',
    'update_photo': 'புகைப்படத்தைப் புதுப்பிக்கவும்',
    // Buyer Dashboard - New Keys
    'buyer_dashboard': 'வாங்குபவர் டாஷ்போர்டு',
    'browse_products_title': 'தயாரிப்புகளைப் பார்க்க',
    'my_orders_title': 'எனது ஆர்டர்கள்',
    'report_issue_title': 'புகாரளிக்கவும்',
    'my_profile_title': 'எனது சுயவிவரம்',
    'total_orders_stat': 'மொத்த ஆர்டர்கள்',
    'all_time_orders': 'அனைத்து கால ஆர்டர்கள்',
    'pending_orders_stat': 'நிலுவையில் உள்ள ஆர்டர்கள்',
    'awaiting_delivery': 'டெலிவரிக்கு காத்திருக்கிறது',
    'completed_orders_stat': 'முடிக்கப்பட்ட ஆர்டர்கள்',
    'successfully_delivered': 'வெற்றிகரமாக வழங்கப்பட்டது',
    'total_spent': 'மொத்த செலவு',
    'lifetime_spending': 'வாழ்நாள் செலவு',
    'welcome_back': 'மீண்டும் வருக',
    'discover_quality_products': 'சரிபார்க்கப்பட்ட MSMEகளிடமிருந்து தரமான ஜவுளி தயாரிப்புகளைக் கண்டறியவும்',
    'start_shopping': 'ஷாப்பிங்கைத் தொடங்குங்கள்',
    // Admin Dashboard - New Keys
    'admin_dashboard': 'நிர்வாக டாஷ்போர்டு',
    'total_users': 'மொத்த பயனர்கள்',
    'buyers_stat': 'வாங்குபவர்கள்',
    'verified_users': 'சரிபார்க்கப்பட்ட பயனர்கள்',
    'manage_users': 'பயனர்களை நிர்வகி',
    'view_issues': 'சிக்கல்களைக் காண்க',
    'audit_logs': 'தணிக்கை பதிவுகள்',
    'user_feedback': 'பயனர் கருத்து',
    'my_products': 'எனது தயாரிப்புகள்',
    'active_products': 'செயலில் உள்ள தயாரிப்புகள்',
    'inactive_products': 'செயலற்ற தயாரிப்புகள்',
    'visible_to_buyers': 'வாங்குபவர்களுக்குத் தெரியும்',
    'no_products_yet': 'இன்னும் தயாரிப்புகள் இல்லை',
    'add_products_to_showcase': 'உங்கள் தயாரிப்புகளைக் காட்ட அவற்றைச் சேர்க்கவும்',
    'update_product': 'தயாரிப்பைப் புதுப்பிக்கவும்',
    'delete_product': 'தயாரிப்பை நீக்கவும்',
    'go_to_inventory_to_add_products': 'தயாரிப்புகளைச் சேர்க்க சரக்குகளை நிர்வகிக்கவும்',
    'inactive_or_out_of_stock': 'செயலற்றது அல்லது கையிருப்பில் இல்லை',
    'inactive': 'செயலற்றது',
    'active': 'செயலில் உள்ளது',
    'yes': 'ஆம்',
    'no': 'இல்லை',
    'active_status': 'செயலில் உள்ளது',
    'inactive_status': 'செயலற்றது',
    'add_inventory_to_msme': 'MSME இல் சரக்குகளைச் சேர்க்கவும்',
    'tax_invoice': 'வரி விலைப்பட்டியல்',
    'original_for_recipient': 'பெறுநருக்கான அசல்',
    'seller_details': 'விற்பனையாளர் விவரங்கள்',
    'buyer_details': 'வாங்குபவர் விவரங்கள்',
    'material_description': 'பொருள் விளக்கம்',
    's_no': 'வ.எண்',
    'uom': 'அலகு',
    'total_amount': 'மொத்த தொகை',
    'terms_conditions': 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
    'computer_generated_invoice': 'இது கணினியால் உருவாக்கப்பட்ட விலைப்பட்டியல் மற்றும் கையொப்பம் தேவையில்லை.',
    'payment_terms': 'விலைப்பட்டியல் தேதியிலிருந்து 30 நாட்களுக்குள் பணம் செலுத்தப்பட வேண்டும்.',
    'goods_sold_terms': 'விற்கப்பட்ட பொருட்கள் திரும்பப் பெறப்பட மாட்டாது அல்லது மாற்றப்பட மாட்டாது.',
    'dispute_terms': 'அனைத்து தகராறுகளும் விற்பனையாளரின் இருப்பிடத்தில் உள்ள நீதிமன்றங்களின் அதிகார வரம்பிற்கு உட்பட்டவை.',
    'interest_terms': 'தாமதமாகச் செலுத்தப்படும் தொகைகளுக்கு ஆண்டுக்கு 18% வட்டி விதிக்கப்படும்.',
    'msme_profile': 'MSME சுயவிவரம்',
    'add_inventory': 'சரக்குகளைச் சேர்',
    'uploading_profile_photo': 'சுயவிவரப் புகைப்படத்தைப் பதிவேற்றுகிறது...',
    'inventory_item_added': 'சரக்கு பொருள் வெற்றிகரமாக சேர்க்கப்பட்டது!',
    'file_size_error': 'கோப்பு அளவு 5MB க்கும் குறைவாக இருக்க வேண்டும்',
    'invalid_image_error': 'தயவுசெய்து சரியான படக் கோப்பைத் தேர்ந்தெடுக்கவும்',
    'invalid_gst_file_error': 'தயவுசெய்து JPEG அல்லது PDF கோப்பைப் பதிவேற்றவும்',
    'attn': 'கவனம்',
    'for': 'அதற்காக',
    'generated_on': 'உருவாக்கப்பட்டது',
    'my_issues_complaints': 'எனது பிரச்சனைகள் மற்றும் புகார்கள்',
    'no_active_issues': 'செயலில் உள்ள சிக்கல்கள் இல்லை',
    'no_resolved_issues': 'தீர்க்கப்பட்ட சிக்கல்கள் இல்லை',
    'admin_response': 'நிர்வாக பதில்',
    'user_profile_details': 'பயனர் சுயவிவர விவரங்கள்',
    'approve_user': 'பயனரை அங்கீகரிக்கவும்',
    'approving': 'அங்கீகரிக்கிறது...',
    'failed_approve_user': 'பயனரை அங்கீகரிக்க முடியவில்லை',
    'confirm_profile_update': 'சுயவிவரப் புதுப்பிப்பை உறுதிப்படுத்தவும்',
    'profile_update_confirm_message': 'உங்கள் சுயவிவரத்தைப் புதுப்பிக்க விரும்புகிறீர்களா? சில மாற்றங்களுக்கு மீண்டும் சரிபார்ப்பு தேவைப்படலாம்.',
    'login_as_guest': 'விருந்தினராக உள்நுழையவும்',
    'close': 'மூடு',
    'stock_utilization': 'சரக்கு பயன்பாடு',
    'overall_stock_usage': 'ஒட்டுமொத்த சரக்கு பயன்பாடு',
    'units_utilized': 'அலகுகள் பயன்படுத்தப்பட்டன',
    'out_of_stock': 'கையிருப்பில் இல்லை',
    'critical': 'முக்கியமானது',
    'low': 'குறைவு',
    'good': 'நல்லது',
    'view_update_catalog': 'உங்கள் தயாரிப்பு பட்டியலைப் பார்த்து புதுப்பிக்கவும்',
    'restock_product': 'பொருளை நிரப்பு',
    'enter_quantity_add': 'சேர்க்க வேண்டிய அளவை உள்ளிடவும்',
    'placing_order': 'ஆர்டர் செய்யப்படுகிறது...',
    'search_products_or_suppliers': 'தயாரிப்புகள் அல்லது சப்ளையர்களைத் தேடுங்கள்...',
    'sort_by': 'இதன்படி வரிசைப்படுத்து',
    'sort_by_name': 'பெயர் படி வரிசைப்படுத்து',
    'sort_by_price': 'விலை படி வரிசைப்படுத்து',
    'sort_by_stock': 'இருப்பு படி வரிசைப்படுத்து',
    'off_line_mode': 'நீங்கள் ஆஃப்லைனில் இருக்கிறீர்கள்',
    'viewing_cached_data': 'கேச் செய்யப்பட்ட தரவைப் பார்க்கிறீர்கள். சில அம்சங்கள் குறைவாக இருக்கலாம்.',
    'reserved': 'ஒதுக்கப்பட்டது',
    'available': 'கிடைக்கக்கூடியது',
    'bought_total_cost': 'வாங்கப்பட்டது (மொத்த செலவு)',
    'track_manage_inventory': 'உங்கள் ஜவுளி சரக்குகளைக் கண்காணித்து நிர்வகிக்கவும்',
    'smart_description': 'ஸ்மார்ட் விளக்கம்',
    'generating': 'உருவாக்கப்படுகிறது...',
    'permanent_deletion': 'நிரந்தர நீக்கம்',
    'action_cannot_be_undone': 'இந்தச் செயலை மாற்ற முடியாது.',
    'manage_fulfill_orders': 'உங்கள் உள்வரும் ஆர்டர்களை நிர்வகிக்கவும் மற்றும் பூர்த்தி செய்யவும்',
    'buyer_gst_number': 'வாங்குபவர் ஜிஎஸ்டி எண்',
    'item_name': 'பொருள் பெயர்',
    'live_data': 'நேரடி தரவு',
    'adding': 'சேர்க்கப்படுகிறது...',
    'loading_inventory_data': 'சரக்குத் தரவை ஏற்றுகிறது...',
    'this_may_take_seconds': 'இதற்கு சில வினாடிகள் ஆகலாம்...',
    'unable_load_stats': 'சரக்கு புள்ளிவிவரங்களை ஏற்ற முடியவில்லை',
    'stock_quantity': 'இருப்பு அளவு',
    'items': 'பொருட்கள்',
    'of': '/',
    'units_utilized_message': 'அலகுகள் பயன்படுத்தப்பட்டன (விற்கப்பட்டவை/ஒதுக்கப்பட்டவை)',
    'enter_name_category': 'தயவுசெய்து முதலில் தயாரிப்பு பெயர் மற்றும் வகையை உள்ளிடவும்.',
    'failed_generate_description': 'விளக்கத்தை உருவாக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'failed_save_item': 'பொருளைச் சேமிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'failed_delete_item': 'பொருளை நீக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'product_name_placeholder': 'உதாரணம்: சீப்பு பருத்தி நூல்',
    'category_placeholder': 'உதாரணம்: மூலப்பொருள்',
    'description_placeholder': 'ஒரு சிறிய, ஈர்க்கக்கூடிய விளக்கம்...',
    'total_spent_placeholder': '₹ மொத்த செலவு',
    'uom_placeholder': 'உதாரணம்: கிலோ, துண்டு',
    'describe_your_product': 'உங்கள் தயாரிப்பு பற்றி விவரிக்கவும்...',
    'inventory_restocked_success': 'தயாரிப்பு வெற்றிகரமாக நிரப்பப்பட்டது!',
    'inventory_item_added_success': 'சரக்கு பொருள் வெற்றிகரமாக சேர்க்கப்பட்டது!',
    'error_restocking': 'தயாரிப்பை நிரப்புவதில் பிழை',
    'new_stock': 'புதிய இருப்பு',
    'error_placing_order': 'கணக்கை உருவாக்குவதில் பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.',
    'showing_other_domains': 'பிற களங்களிலிருந்து தயாரிப்புகளைக் காட்டுகிறது',
    'units_label': 'அலகுகள்',
    'failed_update_status': 'நிலையைப் புதுப்பிக்கத் தவறிவிட்டது',
    'not_applicable': 'பொருந்தாது',
    'please_try_again': 'மீண்டும் முயற்சிக்கவும்',
    'restock_needed_immediately': 'உடனடியாக இருப்பு நிரப்பப்பட வேண்டும்',
    'confirm_restock': 'இருப்பு நிரப்புதலை உறுதிப்படுத்தவும்',
    'units': 'அலகுகள்',
    'total_stock': 'மொத்த இருப்பு',
    'by': 'மூலம்',
    'product': 'தயாரிப்பு',
  }
};
