
import type { Language, MSMEDomain, SalesData, StockData, User } from './types';

export const MOCK_SOCIAL_PROFILES = {
  google: { email: 'google.user@example.com', username: 'Google User', firstname: 'Google' },
  apple: { email: 'apple.user@example.com', username: 'Apple User', firstname: 'Apple' },
  facebook: { email: 'facebook.user@example.com', username: 'Facebook User', firstname: 'Facebook' },
};

export const MSME_DOMAINS: MSMEDomain[] = ['Spinning Mills', 'Knitting and Weaving', 'Dyeing and Finishing', 'Apparel Manufacturing'];

// FIX: Added mock data for dashboard charts
export const MOCK_SALES_DATA: SalesData[] = [
  { month: 'Jan', sales: 400 },
  { month: 'Feb', sales: 300 },
  { month: 'Mar', sales: 500 },
  { month: 'Apr', sales: 700 },
  { month: 'May', sales: 600 },
  { month: 'Jun', sales: 800 },
];

export const MOCK_STOCK_DATA: StockData[] = [
  { date: 'Jan 1', stockLevel: 2400 },
  { date: 'Feb 1', stockLevel: 2210 },
  { date: 'Mar 1', stockLevel: 2290 },
  { date: 'Apr 1', stockLevel: 2000 },
  { date: 'May 1', stockLevel: 2181 },
  { date: 'Jun 1', stockLevel: 2500 },
];

// Demo user configuration - credentials should be set via environment variables
// WARNING: Never hardcode real credentials in production code
type MockUserWithPassword = User & { password?: string };

export const MOCK_USERS: MockUserWithPassword[] = [
  {
    id: 'admin-id',
    email: 'gokulsaravanakumar267@gmail.com',
    password: 'Gokulsha990@',
    username: 'TexConnect Admin',
    firstname: 'Gokul',
    phone: '1234567890',
    address: '123 Admin Lane',
    companyName: 'TexConnect Administration',
    role: 'admin',
    gstNumber: 'ADMIN',
    isApproved: true,
    isEmailVerified: true,
    adminId: 'SUPERADMIN01'
  },
  {
    id: 'msme-1',
    email: 'msme1@example.com',
    username: 'Cotton Mills Ltd',
    firstname: 'Raj',
    phone: '9876543210',
    address: 'Coimbatore, Tamil Nadu',
    companyName: 'Cotton Mills Ltd',
    role: 'msme',
    gstNumber: '33AABCC1234C1Z5',
    isApproved: true,
    isEmailVerified: true,
    domain: 'Spinning Mills'
  },
  {
    id: 'msme-2',
    email: 'msme2@example.com',
    username: 'Textile Weavers',
    firstname: 'Priya',
    phone: '9876543211',
    address: 'Tirupur, Tamil Nadu',
    companyName: 'Textile Weavers Pvt Ltd',
    role: 'msme',
    gstNumber: '33AABCC1234C1Z6',
    isApproved: false,
    isEmailVerified: true,
    domain: 'Knitting and Weaving'
  },
  {
    id: 'buyer-1',
    email: 'buyer1@example.com',
    username: 'Fashion Retail Co',
    firstname: 'Arun',
    phone: '9876543212',
    address: 'Chennai, Tamil Nadu',
    companyName: 'Fashion Retail Co',
    role: 'buyer',
    gstNumber: '33AABCC1234C1Z7',
    isApproved: true,
    isEmailVerified: true
  },
  {
    id: 'buyer-2',
    email: 'buyer2@example.com',
    username: 'Global Exports',
    firstname: 'Meera',
    phone: '9876543213',
    address: 'Bangalore, Karnataka',
    companyName: 'Global Exports Ltd',
    role: 'buyer',
    gstNumber: '29AABCC1234C1Z8',
    isApproved: false,
    isEmailVerified: true
  }
];

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // General
    'texconnect': 'TexConnect',
    'msme_dashboard': 'MSME Dashboard',
    'dashboard': 'Dashboard',
    'inventory': 'Inventory',
    'orders': 'Orders',
    'language': 'Language',
    'english': 'English',
    'tamil': 'Tamil',
    'logout': 'Logout',
    // Auth
    'login': 'Login',
    'register': 'Register',
    'email_address': 'Email Address',
    'password': 'Password',
    'dont_have_account': "Don't have an account?",
    'sign_up': 'Sign Up',
    'already_have_account': 'Already have an account?',
    'full_name': 'Full Name / Business Name',
    'gst_number': 'GST Number',
    'i_am_a': 'I am a...',
    'msme_vendor': 'MSME / Vendor',
    'buyer': 'Buyer',
    'create_account': 'Create Account',
    'login_failed': 'Login failed. Please check your credentials.',
    'registration_successful': 'Registration successful! Please check your email to verify your account.',
    'email_not_verified': 'Your email is not verified. A new verification link has been sent.',
    'resend_verification': 'Resend Verification Email',
    'domain': 'Domain',
    'select_domain': 'Select your domain',
    'spinning_mills': 'Spinning Mills',
    'knitting_and_weaving': 'Knitting and Weaving',
    'dyeing_and_finishing': 'Dyeing and Finishing',
    'apparel_manufacturing': 'Apparel Manufacturing',
    // Pending Approval
    'pending_approval': 'Account Pending Approval',
    'pending_approval_message': 'Your account has been registered and is awaiting approval from an administrator. Please check back later.',
    // Verify Email
    'verify_your_email': 'Verify Your Email',
    'verification_email_sent': 'A verification link has been sent to your email address. Please click the link to activate your account.',
    'simulate_verification': 'Simulate Email Verification',
    // Dashboard View
    'dashboard_overview': 'Dashboard Overview',
    'total_stock_value': 'Total Stock Value',
    'pending_orders': 'Pending Orders',
    'items_in_stock': 'Items in Stock',
    'revenue_this_month': 'Revenue (This Month)',
    'sales_trends': 'Sales Trends',
    'stock_levels': 'Stock Levels',
    'total_products': 'Total Products',
    'current_stock': 'Current Stock',
    'low_stock_items': 'Low Stock Items',
    // Inventory View
    'manage_inventory': 'Manage Inventory',
    'add_new_item': 'Add New Item',
    'product_name': 'Product Name',
    'category': 'Category',
    'stock': 'Stock',
    'price_per_unit': 'Price (₹)/unit',
    'actions': 'Actions',
    'description': 'Description',
    'edit': 'Edit',
    'delete': 'Delete',

    'restock': 'Restock',
    'initial_stock': 'Initial Stock',
    'edit_item': 'Edit Item',
    'save_changes': 'Save Changes',
    'cancel': 'Cancel',
    'confirm_delete': 'Are you sure you want to delete this item?',
    'delete_item': 'Delete Item',
    'unit_of_measure': 'Unit of Measure',
    'minimum_stock_level': 'Minimum Stock Level',
    'stock_alert': 'Low Stock',
    // Orders View
    'track_orders': 'Track Orders',
    'order_id': 'Order ID',
    'buyer_name': 'Buyer Name',
    'date': 'Date',
    'status': 'Status',
    'total': 'Total (₹)',
    'update_status': 'Update Status',
    'no_orders': 'No orders found.',
    'no_inventory': 'No inventory items found. Add one to get started!',
    'buyer_gst': 'Buyer GST',
    // Buyer View
    'buyer_portal': 'Buyer Portal',
    'browse_products': 'Browse Products',
    'my_orders': 'My Orders',
    'search_products': 'Search for products...',
    'place_order': 'Place Order',
    'available_stock': 'Available Stock',
    'quantity': 'Quantity',
    'confirm_order': 'Confirm Order',
    'no_products_found': 'No products found matching your search.',
    'your_orders': 'Your Orders',
    'filter_by_domain': 'Filter by Domain',
    'all_domains': 'All Domains',
    // MSME Profile
    'profile': 'Profile',
    'your_profile': 'Your Profile',
    'edit_profile': 'Edit Profile',
    'pending_changes_message': 'Your profile updates are waiting for an administrator to review and approve them.',
    'gst_certificate': 'GST Certificate',
    'view_certificate': 'View Certificate',
    'not_uploaded': 'Not Uploaded',
    // Invoice
    'invoice': 'Invoice',
    'download_pdf': 'Download PDF',
    'invoice_no': 'Invoice No.',
    'invoice_date': 'Invoice Date',
    'order_date': 'Order Date',
    'bill_to': 'Bill To',
    'ship_to': 'Ship To',
    'item_description': 'Item Description',
    'qty': 'Qty',
    'rate': 'Rate (₹)',
    'amount': 'Amount (₹)',
    'subtotal': 'Subtotal',
    'gst_18': 'GST (18%)',
    'grand_total': 'Grand Total',
    'authorized_signatory': 'Authorized Signatory',
    // Admin View
    'admin_panel': 'Admin Panel',
    'user_management': 'User Management',
    'user_name': 'User Name',
    'role': 'Role',
    'approval_status': 'Approval Status',
    'approve': 'Approve',
    'approved': 'Approved',
    'pending': 'Pending',
    'review_changes': 'Review Changes',
    'approve_changes': 'Approve Changes',
    'reject_changes': 'Reject Changes',
    'current_information': 'Current Information',
    'proposed_changes': 'Proposed Changes',
    'admin_type': 'Admin Type',
    'msme': 'MSME',
    'admin': 'Admin',
    // Approvals
    'msme_approvals': 'MSME Approvals',
    'buyer_approvals': 'Buyer Approvals',
    'admin_management': 'Admin Management',
    'audit_log': 'Audit Log',
    'feedback_logs': 'Feedback Logs',
    'issue_logs': 'Issue Logs',
    'address': 'Address',
    'verified': 'Verified',
    'unverified': 'Unverified',
    'pending_review': 'Pending Review',
    'reject': 'Reject',
    'view': 'View',
    'switch_admin': 'Switch Admin',
    'admin_profile_title': 'Admin Profile',
    'change_photo': 'Change profile picture',
    'settings': 'Settings',
    'loading': 'Loading',
    'login_required_profile': 'Please log in to view profile.',
    'you': 'You',
    'not_set': 'Not set',
    'uploading': 'Uploading',
    'error': 'Error',
    'profile_updated_success': 'Profile updated successfully!',
    'enter_username': 'Enter your username',
    'enter_phone': 'Enter your phone number',
    'enter_address': 'Enter your address',
    'saving': 'Saving',
    'quick_actions': 'Quick Actions',
    'system_overview': 'System Overview',
    'system_status': 'System Status',
    'database_connected': 'Database Connected',
    'online': 'Online',
    'system_performance': 'System Performance',
    'optimal': 'Optimal',
    'pending_tasks': 'Pending Tasks',
    'users_pending_verification': 'Users pending verification',
    'no_pending_tasks': 'No pending tasks.',
    'low_stock': 'low stock',
    'orders_count': 'orders',
    'order_placed': 'Order placed',
    'stock_updated': 'Stock updated',
    'item_shipped': 'Item shipped',
    'new_product_added': 'New product added',
    'approved_status': 'Approved',
    'pending_approval_status': 'Pending Approval',
    'add_inventory_action': 'Add Inventory',
    'new_order_action': 'New Order',
    'export_report_action': 'Export Report',
    'view_alerts_action': 'View Alerts',
    'just_now': 'Just now',
    'min_ago': 'min ago',
    'h_ago': 'h ago',
    'd_ago': 'd ago',
    // Company Profile
    'company_profile': 'Company Profile',
    'choose_company_photo': 'Choose company profile photo',
    'company_name': 'Company Name',
    'contact_person': 'Contact Person',
    'email': 'Email',
    'phone': 'Phone',
    // Issues Page
    'issues': 'Issues',
    'report_issue': 'Report Issue',
    'issue_title': 'Issue Title',
    'issue_description': 'Issue Description',
    'issue_category': 'Issue Category',
    'issue_priority': 'Issue Priority',
    'active_issues': 'Active Issues',
    'resolved_issues': 'Resolved Issues',
    'no_issues': 'No issues',
    'report_new_issue': 'Report New Issue',
    // Buyer Dashboard - New Keys
    'buyer_dashboard': 'Buyer Dashboard',
    'browse_products_title': 'Browse Products',
    'my_orders_title': 'My Orders',
    'report_issue_title': 'Report Issue',
    'my_profile_title': 'My Profile',
    'total_orders_stat': 'Total Orders',
    'all_time_orders': 'All time orders',
    'pending_orders_stat': 'Pending Orders',
    'awaiting_delivery': 'Awaiting delivery',
    'completed_orders_stat': 'Completed Orders',
    'successfully_delivered': 'Successfully delivered',
    'total_spent': 'Total Spent',
    'lifetime_spending': 'Lifetime spending',
    'welcome_back': 'Welcome back',
    'discover_quality_products': 'Discover quality textile products from verified MSMEs',
    'start_shopping': 'Start Shopping',
    // Admin Dashboard - New Keys
    'admin_dashboard': 'Admin Dashboard',
    'total_users': 'Total Users',
    'buyers_stat': 'Buyers',
    'verified_users': 'Verified Users',
    'manage_users': 'Manage Users',
    'view_issues': 'View Issues',
    'audit_logs': 'Audit Logs',
    'user_feedback': 'User Feedback',
  },
  ta: {
    // General
    'texconnect': 'டெக்ஸ்கனெக்ட்',
    'msme_dashboard': 'குறு, சிறு மற்றும் நடுத்தர நிறுவன டாஷ்போர்டு',
    'dashboard': 'டாஷ்போர்டு',
    'inventory': 'சரக்கு',
    'orders': 'ஆர்டர்கள்',
    'language': 'மொழி',
    'english': 'ஆங்கிலம்',
    'tamil': 'தமிழ்',
    'logout': 'வெளியேறு',
    // Auth
    'login': 'உள்நுழை',
    'register': 'பதிவு செய்',
    'email_address': 'மின்னஞ்சல் முகவரி',
    'password': 'கடவுச்சொல்',
    'dont_have_account': 'கணக்கு இல்லையா?',
    'sign_up': 'பதிவு செய்க',
    'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'full_name': 'முழு பெயர் / வணிகப் பெயர்',
    'gst_number': 'ஜிஎஸ்டி எண்',
    'i_am_a': 'நான் ஒரு...',
    'msme_vendor': 'குறு, சிறு மற்றும் நடுத்தர தொழில் / விற்பனையாளர்',
    'buyer': 'வாங்குபவர்',
    'create_account': 'கணக்கை உருவாக்கு',
    'login_failed': 'உள்நுழைவு தோல்வியடைந்தது. உங்கள் சான்றுகளைச் சரிபார்க்கவும்.',
    'registration_successful': 'பதிவு வெற்றி பெற்றது! உங்கள் கணக்கைச் சரிபார்க்க உங்கள் மின்னஞ்சலைச் சரிபார்க்கவும்.',
    'email_not_verified': 'உங்கள் மின்னஞ்சல் சரிபார்க்கப்படவில்லை. ஒரு புதிய சரிபார்ப்பு இணைப்பு அனுப்பப்பட்டுள்ளது.',
    'resend_verification': 'சரிபார்ப்பு மின்னஞ்சலை மீண்டும் அனுப்பு',
    'domain': 'களம்',
    'select_domain': 'உங்கள் களத்தைத் தேர்ந்தெடுக்கவும்',
    'spinning_mills': 'நூற்பு ஆலைகள்',
    'knitting_and_weaving': 'பின்னல் மற்றும் நெசவு',
    'dyeing_and_finishing': 'சாயமிடுதல் மற்றும் முடித்தல்',
    'apparel_manufacturing': 'ஆடை உற்பத்தி',
    // Pending Approval
    'pending_approval': 'கணக்கு ஒப்புதலுக்காக காத்திருக்கிறது',
    'pending_approval_message': 'உங்கள் கணக்கு பதிவு செய்யப்பட்டு நிர்வாகியின் ஒப்புதலுக்காக காத்திருக்கிறது. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪರಿಶೀಲಿಸಿ.',
    // Verify Email
    'verify_your_email': 'உங்கள் மின்னஞ்சலைச் சரிபார்க்கவும்',
    'verification_email_sent': 'உங்கள் மின்னஞ்சல் முகவரிக்கு ஒரு சரிபார்ப்பு இணைப்பு அனுப்பப்பட்டுள்ளது. உங்கள் கணக்கைச் செயல்படுத்த இணைப்பைக் கிளிக் செய்யவும்.',
    'simulate_verification': 'மின்னஞ்சல் சரிபார்ப்பை உருவகப்படுத்துங்கள்',
    // Dashboard View
    'dashboard_overview': 'டாஷ்போர்டு கண்ணோட்டம்',
    'total_stock_value': 'மொத்த சரக்கு மதிப்பு',
    'pending_orders': 'நிலுவையில் உள்ள ஆர்டர்கள்',
    'items_in_stock': 'கையிருப்பில் உள்ள பொருட்கள்',
    'revenue_this_month': 'வருவாய் (இந்த மாதம்)',
    'sales_trends': 'விற்பனை போக்குகள்',
    'stock_levels': 'சரக்கு நிலைகள்',
    'total_products': 'மொத்த தயாரிப்புகள்',
    'current_stock': 'தற்போதைய இருப்பு',
    'low_stock_items': 'குறைந்த இருப்பு பொருட்கள்',
    // Inventory View
    'manage_inventory': 'சரக்குகளை நிர்வகி',
    'add_new_item': 'புதிய பொருளைச் சேர்',
    'product_name': 'பொருளின் பெயர்',
    'category': 'வகை',
    'stock': 'சரக்கு',
    'price_per_unit': 'விலை (₹)/அலகு',


    'restock': 'சரக்கை நிரப்பு',
    'initial_stock': 'ஆரம்ப இருப்பு',
    'edit_item': 'பொருளைத் திருத்து',
    'save_changes': 'மாற்றங்களைச் சேமி',
    'cancel': 'ரத்துசெய்',
    'confirm_delete': 'இந்த பொருளை நீக்க விரும்புகிறீர்களா?',
    'delete_item': 'பொருளை நீக்கு',
    'unit_of_measure': 'அளவீட்டு அலகு',
    'minimum_stock_level': 'குறைந்தபட்ச இருப்பு நிலை',
    'stock_alert': 'குறைந்த இருப்பு',
    // Orders View
    'track_orders': 'ஆர்டர்களைக் கண்காணி',
    'order_id': 'ஆர்டர் ஐடி',
    'buyer_name': 'வாங்குபவர் பெயர்',
    'date': 'தேதி',
    'status': 'நிலை',
    'total': 'மொத்தம் (₹)',
    'update_status': 'நிலையை மாற்று',
    'no_orders': 'ஆர்டர்கள் எதுவும் இல்லை.',
    'no_inventory': 'சரக்குப் பொருட்கள் எதுவும் இல்லை. தொடங்குவதற்கு ஒன்றைச் சேர்க்கவும்!',
    'buyer_gst': 'வாங்குபவர் ஜிஎஸ்டி',
    // Buyer View
    'buyer_portal': 'வாங்குபவர் போர்டல்',
    'browse_products': 'தயாரிப்புகளை உலாவுக',
    'my_orders': 'என் ಆದೇಶಗಳು',
    'search_products': 'தயாரிப்புகளைத் தேடுங்கள்...',
    'place_order': 'ஆர்டர் செய்',
    'available_stock': 'கிடைக்கும் சரக்கு',
    'quantity': 'அளவு',
    'confirm_order': 'உறுதி செய்',
    'no_products_found': 'உங்கள் தேடலுடன் பொருந்தும் தயாரிப்புகள் எதுவும் இல்லை.',
    'your_orders': 'உங்கள் ஆர்டர்கள்',
    'filter_by_domain': 'களம் வாரியாக வடிகட்டவும்',
    'all_domains': 'அனைத்து களங்களும்',
    // MSME Profile
    'profile': 'சுயவிவரம்',
    'your_profile': 'உங்கள் சுயவிவரம்',
    'edit_profile': 'சுயவிவரத்தைத் திருத்து',
    'pending_changes_message': 'உங்கள் சுயவிவரப் புதுப்பிப்புகள் நிர்வாகி மதிப்பாய்வு செய்து ஒப்புதல் அளிப்பதற்காகக் காத்திருக்கின்றன.',
    'gst_certificate': 'ஜிஎஸ்டி சான்றிதழ்',
    'view_certificate': 'சான்றிதழைப் காண்க',
    'not_uploaded': 'பதிவேற்றப்படவில்லை',
    // Invoice
    'invoice': 'விலைப்பட்டியல்',
    'download_pdf': 'PDF பதிவிறக்கம்',
    'invoice_no': 'விலைப்பட்டியல் எண்.',
    'invoice_date': 'விலைப்பட்டியல் தேதி',
    'order_date': 'ஆர்டர் தேதி',
    'bill_to': 'யாருக்கு பட்டியல்',
    'ship_to': 'யாருக்கு அனுப்பவேண்டியது',
    'item_description': 'பொருள் விவரம்',
    'qty': 'அளவு',
    'rate': 'விகிதம் (₹)',
    'amount': 'தொகை (₹)',
    'subtotal': 'மொத்த தொகை',
    'gst_18': 'ஜிஎஸ்டி (18%)',
    'grand_total': 'மொத்த கூட்டுத்தொகை',
    'authorized_signatory': 'அங்கீகரிக்கப்பட்ட கையொப்பமிட்டவர்',
    // Admin View
    'admin_panel': 'நிர்வாக குழு',
    'user_management': 'பயனர் மேலாண்மை',
    'user_name': 'பயனர் பெயர்',
    'role': 'பங்கு',
    'approval_status': 'ஒப்புதல் நிலை',
    'approve': 'ஒப்புதல்',
    'approved': 'ஒப்புதல் அளிக்கப்பட்டது',
    'pending': 'நிலுவையில்',
    'review_changes': 'மாற்றங்களை மதிப்பாய்வு செய்',
    'approve_changes': 'மாற்றங்களை அங்கீகரிக்கவும்',
    'reject_changes': 'மாற்றங்களை நிராகரிக்கவும்',
    'current_information': 'தற்போதைய தகவல்',
    'proposed_changes': 'பரிந்துரைக்கப்பட்ட மாற்றங்கள்',
    'admin_type': 'நிர்வாகி வகை',
    'msme': 'MSME',
    'admin': 'நிர்வாகி',
    // Approvals
    'msme_approvals': 'MSME ஒப்புதல்கள்',
    'buyer_approvals': 'வாங்குபவர் ஒப்புதல்கள்',
    'admin_management': 'நிர்வாகி மேலாண்மை',
    'audit_log': 'தணிக்கை பதிவு',
    'feedback_logs': 'கருத்து பதிவுகள்',
    'issue_logs': 'சிக்கல் பதிவுகள்',
    'address': 'முகவரி',
    'verified': 'சரிபார்க்கப்பட்ட',
    'unverified': 'சரிபார்க்கப்படவில்லை',
    'pending_review': 'மதிப்பாய்வு நிலுவையில் உள்ளது',
    'reject': 'நிராகரிக்க',
    'view': 'பார்க்க',
    'switch_admin': 'நிர்வாகியை மாற்றவும்',
    'admin_profile_title': 'நிர்வாக சுயவிவரம்',
    'change_photo': 'சுயவிவரப் படத்தை மாற்றவும்',
    'settings': 'அமைப்புகள்',
    'loading': 'ஏற்றுகிறது',
    'login_required_profile': 'சுயவிவரத்தைப் பார்க்க உள்நுழையவும்.',
    'you': 'நீங்கள்',
    'not_set': 'அமைக்கப்படவில்லை',
    'uploading': 'பதிவேற்றுகிறது',
    'error': 'பிழை',
    'profile_updated_success': 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    'enter_username': 'உங்கள் பயனர் பெயரை உள்ளிடவும்',
    'enter_phone': 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
    'enter_address': 'உங்கள் முகவரியை உள்ளிடவும்',
    'saving': 'சேமிக்கிறது',
    'quick_actions': 'விரைவான நடவடிக்கைகள்',
    'system_overview': 'அமைப்பு மேலோட்டம்',
    'system_status': 'அமைப்பு நிலை',
    'database_connected': 'தரவுத்தளம் இணைக்கப்பட்டுள்ளது',
    'online': 'ஆன்லைன்',
    'system_performance': 'அமைப்பு செயல்திறன்',
    'optimal': 'உகந்த',
    'pending_tasks': 'நிலுவையில் உள்ள பணிகள்',
    'users_pending_verification': 'பயனர்கள் சரிபார்ப்பு நிலுவையில் உள்ளது',
    'no_pending_tasks': 'நிலுவையில் உள்ள பணிகள் இல்லை.',
    'low_stock': 'குறைந்த இருப்பு',
    'orders_count': 'ஆர்டர்கள்',
    'order_placed': 'ஆர்டர் செய்யப்பட்டது',
    'stock_updated': 'இருப்பு புதுப்பிக்கப்பட்டது',
    'item_shipped': 'பொருள் அனுப்பப்பட்டது',
    'new_product_added': 'புதிய தயாரிப்பு சேர்க்கப்பட்டது',
    'approved_status': 'அங்கீகரிக்கப்பட்டது',
    'pending_approval_status': 'ஒப்புதலுக்காக காத்திருக்கிறது',
    'add_inventory_action': 'சரக்குகளைச் சேர்',
    'new_order_action': 'புதிய ஆர்டர்',
    'export_report_action': 'அறிக்கையை ஏற்றுமதி செய்',
    'view_alerts_action': 'எச்சரிக்கைகளைப் பார்க்கவும்',
    'just_now': 'இப்பொழுது',
    'min_ago': 'நிமிடங்களுக்கு முன்',
    'h_ago': 'மணிநேரங்களுக்கு முன்',
    'd_ago': 'நாட்களுக்கு முன்',
    // Company Profile
    'company_profile': 'நிறுவன சுயவிவரம்',
    'choose_company_photo': 'நிறுவன சுயவிவர புகைப்படத்தைத் தேர்ந்தெடுக்கவும்',
    'company_name': 'நிறுவன பெயர்',
    'contact_person': 'தொடர்பு நபர்',
    'email': 'மின்னஞ்சல்',
    'phone': 'தொலைபேசி',
    // Issues Page
    'issues': 'சிக்கல்கள்',
    'report_issue': 'சிக்கலைப் புகாரளி',
    'issue_title': 'சிக்கலின் தலைப்பு',
    'issue_description': 'சிக்கலின் விளக்கம்',
    'issue_category': 'சிக்கலின் வகை',
    'issue_priority': 'சிக்கலின் முன்னுரிமை',
    'active_issues': 'செயல்பாட்டில் உள்ள சிக்கல்கள்',
    'resolved_issues': 'தீர்க்கப்பட்ட சிக்கல்கள்',
    'no_issues': 'சிக்கல்கள் இல்லை',
    'report_new_issue': 'புதிய சிக்கலைப் புகாரளி',
    // Buyer Dashboard - New Keys
    'buyer_dashboard': 'வாங்குபவர் டாஷ்போர்டு',
    'browse_products_title': 'தயாரிப்புகளைப் பார்க்க',
    'my_orders_title': 'எனது ஆர்டர்கள்',
    'report_issue_title': 'புகாரளிக்கவும்',
    'my_profile_title': 'எனது சுயவிவரம்',
    'total_orders_stat': 'மொத்த ஆர்டர்கள்',
    'all_time_orders': 'அனைத்து கால ஆர்டர்கள்',
    'pending_orders_stat': 'நிலுவையில் உள்ள ஆர்டர்கள்',
    'awaiting_delivery': 'டெலிவரிக்கு காத்திருக்கிறது',
    'completed_orders_stat': 'முடிக்கப்பட்ட ஆர்டர்கள்',
    'successfully_delivered': 'வெற்றிகரமாக வழங்கப்பட்டது',
    'total_spent': 'மொத்த செலவு',
    'lifetime_spending': 'வாழ்நாள் செலவு',
    'welcome_back': 'மீண்டும் வருக',
    'discover_quality_products': 'சரிபார்க்கப்பட்ட MSMEகளிடமிருந்து தரமான ஜவுளி தயாரிப்புகளைக் கண்டறியவும்',
    'start_shopping': 'ஷாப்பிங்கைத் தொடங்குங்கள்',
    // Admin Dashboard - New Keys
    'admin_dashboard': 'நிர்வாக டாஷ்போர்டு',
    'total_users': 'மொத்த பயனர்கள்',
    'buyers_stat': 'வாங்குபவர்கள்',
    'verified_users': 'சரிபார்க்கப்பட்ட பயனர்கள்',
    'manage_users': 'பயனர்களை நிர்வகி',
    'view_issues': 'சிக்கல்களைக் காண்க',
    'audit_logs': 'தணிக்கை பதிவுகள்',
    'user_feedback': 'பயனர் கருத்து',
  }
};
